apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
  labels:
    app: my-app
    color: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      color: green
  template:
    metadata:
      labels:
        app: my-app
        color: green
    spec:
      containers:
      - name: my-app
        image: project_task/my-app:green-2024-03-10
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-green-service
spec:
  selector:
    app: my-app
    color: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  
